service: serverless-tutorial
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: /hello

  helloUser:
    handler: handler.helloUser
    events:
      - http:
          method: GET
          path: /helloUser/{name}

plugins:
  - serverless-offline
