name: Continues Delivery

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ matrix.os }}-modules-${{ hashFiles('**/package-json.lock') }}

      - name: Install dependencies
        run: npm install

      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
